version: 0.2

phases:
    build:
        commands:
        - echo "This is build phase... zipping webpage"
    
    post_builds:
        commands:
        - echo "Deployed to s3"
artifacts:
    files:
      - '**/*'
